name = "QUBOConstraints"
uuid = "110b7fcc-6942-4061-a625-86e03d1de7cf"
authors = ["azzaare <jf@baffier.fr> and contributors"]
version = "0.1.2"

[deps]
ConstraintDomains = "5800fd60-8556-4464-8d61-84ebf7a0bedb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
ConstraintDomains = "0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
